CREATE
TABLE IF NOT EXISTS USER_PROFILES(
    ID BIGSERIAL PRIMARY KEY,
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME TEXT NOT NULL,
    EMAIL TEXT UNIQUE NOT NULL,
    GENDER TEXT CHECK(GENDER IN('ERKEK', 'KADIN')) NOT NULL,
    CREATE_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

--USER_PROFILE_ID BU SENARYODA HEM PK HEM FK'DIR.
CREATE
TABLE IF NOT EXISTS YOUTUBE_ACCOUNTS(
    USER_PROFILE_ID BIGINT PRIMARY KEY REFERENCES USER_PROFILES(ID),
    CREATE_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE
TABLE IF NOT EXISTS YOUTUBE_CHANNELS(
    ID BIGSERIAL PRIMARY KEY,
    YOUTUBE_ACCOUNT_ID BIGINT NOT NULL REFERENCES YOUTUBE_ACCOUNTS(USER_PROFILE_ID),
    CHANNEL_NAME TEXT NOT NULL UNIQUE,
    CREATE_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

--YOUTUBE_ACCOUNT_ID VE YOUTUBE_CHANNEL_ID BU SENARYODA HEM PK HEM FK'DIR.
CREATE
TABLE IF NOT EXISTS CHANNEL_SUBSCRIBERS(
    YOUTUBE_ACCOUNT_ID BIGINT REFERENCES YOUTUBE_ACCOUNTS(ID),
    YOUTUBE_CHANNEL_ID BIGINT REFERENCES YOUTUBE_CHANNEL(ID),
    CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY (YOUTUBE_ACCOUNT_ID, YOUTUBE_CHANNEL_ID)
);

SELECT *
FROM USER_PROFILES;

SELECT *
FROM YOUTUBE_ACCOUNTS;

SELECT *
FROM YOUTUBE_CHANNELS;

SELECT *
FROM CHANNEL_SUBSCRIBERS;

SELECT *
FROM USER_PROFILES
LEFT JOIN YOUTUBE_ACCOUNTS YA
ON USER_PROFILES.ID = YA.ID
LEFT JOIN CHANNEL_SUBSCRIBERS
ON YA.ID = CHANNEL_SUBSCRIBERS.YOUTUBE_ACCOUNT_ID
LEFT JOIN YOUTUBE_CHANNELS YC CHANNEL_SUBSCRIBERS.YOUTUBE_CHANNEL_ID;
